CREATE USER bank_app IDENTIFIED BY g54nuu;
/

GRANT CONNECT TO bank_app;
/

GRANT SELECT, INSERT, UPDATE, DELETE ON BANK_APP.Accounts TO bank_app;
/
GRANT SELECT, INSERT, UPDATE, DELETE ON BANK_APP.Users TO bank_app;
/
GRANT SELECT, INSERT, UPDATE, DELETE ON BANK_APP.User_Types TO bank_app;
/
GRANT SELECT, INSERT, UPDATE, DELETE ON BANK_APP.User_account_Joint TO bank_app;
/
GRANT SELECT ANY SEQUENCE TO bank_app;
/